Update 1_chapter1.tex
BITNP/BIThesis pull request #148
Opened 2022-06-18 12:28 UTC by Hibiscus-2333

表格方面改为三线表制，用/toprule和/bottomrule替代/hline，去掉多余的/hline

2022-06-20 15:19 UTC, fky2015 requested changes

2022-06-20 15:19 UTC, fky2015 commented on templates/undergraduate-thesis/chapters/1_chapter1.tex
>  \end{table}
可以删除掉原有的表格。

2022-06-24 01:41 UTC, Hibiscus-2333 commented on templates/undergraduate-thesis/chapters/1_chapter1.tex
>  \end{table}
已修改。

2022-06-26 14:42 UTC, fky2015 requested changes

2022-06-26 14:42 UTC, fky2015 commented on templates/undergraduate-thesis/chapters/1_chapter1.tex
> +% \end{table}
可以直接删除（而不是注释），旧代码主要通过 Git 进行管理。

2022-07-03 11:11 UTC, fky2015 approved these changes
LGTM

2022-07-03 11:50 UTC, merged