针对研究生院官网发布而添加的快速使用手册
BITNP/BIThesis pull request #242
Opened 2023-02-27 01:30 UTC by fky2015

2023-03-03 09:11 UTC, spencerwooo commented
周末我可以帮助完善此分支，推荐从哪里开始？

2023-03-03 09:19 UTC, fky2015 commented
> 周末我可以帮助完善此分支，推荐从哪里开始？

哇，这个帮助太及时了。
目前我的全部进度就是以上这些。然后正好我这两周都没太多时间完成这个 PR。所以你可以从任意的地方开始。

基本流程就是：
1. 首先参考原有模板提供的使用手册。
2. 然后详细配置的部分可以指引用户直接看现成的手册（配置部分）或者在线 wiki（安装部分）。

你可以直接 push 这个分支。

2023-10-07 06:19 UTC, YDX-2147483647 commented on the-graduates-handbook/chapters/ch0-quick-start.tex
> +访问 \url{https://bithesis.bitnp.net}，点击右上角的 ``模板下载'' ，跳转到 BITHesis 项目的 GitHub Releases 页面（也即 \url{https://github.com/BITNP/BIThesis/releases/latest}）。选择相应的模板压缩包并下载。
这几处“相应的”“需要的”要不要改成具体所指？

2023-10-07 09:41 UTC, YDX-2147483647 commented on the-graduates-handbook/chapters/ch0-quick-start.tex
> +访问 \url{https://bithesis.bitnp.net}，点击右上角的 ``模板下载'' ，跳转到 BITHesis 项目的 GitHub Releases 页面（也即 \url{https://github.com/BITNP/BIThesis/releases/latest}）。选择相应的模板压缩包并下载。
另：这里的 BIThesis 大小写和别处不同。为什么没用那个 $\LaTeX$ 一样的宏呢？

2023-10-07 14:12 UTC, fky2015 commented on the-graduates-handbook/chapters/ch0-quick-start.tex
> +访问 \url{https://bithesis.bitnp.net}，点击右上角的 ``模板下载'' ，跳转到 BITHesis 项目的 GitHub Releases 页面（也即 \url{https://github.com/BITNP/BIThesis/releases/latest}）。选择相应的模板压缩包并下载。
> 另：这里的 BIThesis 大小写和别处不同。为什么没用那个 LATEX 一样的宏呢？

typo 我修一下。没有用 `\BIThesis` 是因为那个宏没有放到 bithesis.cls 里面，我也同意未来可以加一下。

2023-10-08 10:30 UTC, YDX-2147483647 commented on the-graduates-handbook/main.tex
> +\input{chapters/acknowledgements.tex}
致谢现在是原始模板，要不要删除？

2023-10-08 10:36 UTC, YDX-2147483647 requested changes
可否加一下`hyperref`之类的？手册中有一些链接，现在很难辨识……

![图片](https://github.com/BITNP/BIThesis/assets/73375426/f7418508-b236-49e8-9863-69fdeda2829f)

![图片](https://github.com/BITNP/BIThesis/assets/73375426/b6516168-9cc6-4f69-a8c5-b3c3cf2ef605)

2023-10-08 17:06 UTC, fky2015 commented
> 可否加一下`hyperref`之类的？手册中有一些链接，现在很难辨识……
> 
> ![图片](https://user-images.githubusercontent.com/73375426/273443371-f7418508-b236-49e8-9863-69fdeda2829f.png)
> 
> ![图片](https://user-images.githubusercontent.com/73375426/273443399-b6516168-9cc6-4f69-a8c5-b3c3cf2ef605.png)

Done!

2023-10-08 17:18 UTC, fky2015 commented on the-graduates-handbook/main.tex
> +\input{chapters/acknowledgements.tex}
已经补充致谢内容。

2023-10-09 02:25 UTC, YDX-2147483647 commented on Makefile
> +	cp ./the-graduates-handbook/main.pdf ${GRAD_DEST_DIR}-${version}/"研究生学位论文模板快速使用手册".pdf
请问`"研究生学位论文模板快速使用手册".pdf`能否改成单引号？我这儿单引号或不加引号正常，双引号的话会提示`"`不匹配，似乎是双引号导致 GB 18030 / UTF-8 串了，然后`"`混到汉字结尾的字节里了。

```shell
/usr/bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
```

不过我这儿是 Windows，实在不行可忽略。

2023-10-09 04:39 UTC, fky2015 commented on Makefile
> +	cp ./the-graduates-handbook/main.pdf ${GRAD_DEST_DIR}-${version}/"研究生学位论文模板快速使用手册".pdf
Done

2023-10-09 05:25 UTC, YDX-2147483647 approved these changes

2023-10-09 06:19 UTC, merged