Update issue templates
BITNP/BIThesis pull request #99
Opened 2022-01-07 02:34 UTC by fky2015

2022-01-07 15:43 UTC, phy25 requested changes
I know this is a draft but...

Any chance to rename this file (might be generated through the Chinese title)?

2022-01-07 15:43 UTC, phy25 commented on .github/ISSUE_TEMPLATE/------.md
> + - Browser [e.g. chrome, safari]
Is this needed?

2022-01-08 06:13 UTC, fky2015 commented
> I know this is a draft but...
> 
> Any chance to rename this file (might be generated through the Chinese title)?

Will do.

2022-01-20 12:42 UTC, everything411 commented
LGTM

2022-01-20 12:55 UTC, everything411 approved these changes
LGTM

2022-01-20 12:56 UTC, merged